### ISSUE TITLE
Cant setup integration

### ISSUE THREAD

**Issue by Lux315** [iKaew/hass-linkstation-addon#4]
Hello,

tried setting up the integration and i get this error (All given config information is exact what im logging into the nas with): 

`Error setting up entry NAS for linkstation
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 388, in async_setup
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/linkstation/__init__.py", line 123, in async_setup_entry
    hass.config_entries.async_setup_platforms(config_entry, PLATFORMS)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'ConfigEntries' object has no attribute 'async_setup_platforms'`

**Comment by iKaew** [comment]
Hi 

What's the Home assistant version?  Did you put the configuration in configuration.yml yet ?

**Comment by Lux315** [comment]
Hi,

Version is 2023.8.2

Yes the configuration is in configuration.yaml exactly like given in the docs, ive checked them and theyre right.

The linkstation is a LS-WXL Linkstation Duo

linkstation:
  name: NAS
  host: 192.168.178.134
  username: !secret linkstation_username
  password: !secret linkstation_password
  scan_interval: 30 # minutes

**Comment by koggaccio** [comment]
same problem

**Comment by Harlekien** [comment]
Hello,
I have also an issue with the integration.
**Log**
`             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/linkstation/__init__.py", line 123, in async_setup_entry
    hass.config_entries.async_setup_platforms(config_entry, PLATFORMS)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'ConfigEntries' object has no attribute 'async_setup_platforms'. Did you mean: 'async_unload_platforms'?`

**configuration.yaml**
linkstation:
    name: LinkStation
    host: 192.168.178.5 # LinkStation IP Address
    username: !secret linkstation_username
    password: !secret linkstation_password
    scan_interval: 10 # minutes


Home Assistant Version Core: 2024.6.1
Home Assisant Operation System: 12.3

**Comment by iKaew** [comment]
This should get fixed in latest version
